### PR TITLE
Issue 1

### PR DESCRIPTION
**Pull request by tk721**
Fixes Issue #1 by adding a constant guard to all Debug.p() statements. The constant is defined in Core.Constants.DEBUG and is false by default.

### CODE REVIEW

**Comment by akeranen** [comment]
Could this be rather done by simply adding the guard to the Debug class making the print calls empty and hence compiled out? Prefixing all debug prints with `if (DEBUG)` sounds a bit tedious. And could be worthwhile to try with profiler what is the benefit of doing this.

**Comment by tk721** [comment]
If the guard is outside the Debug class the whole statement gets compiled out. If it's inside, the call to Debug remains, as does the work to build the string to be logged. The performance impact of course depends on how often Debug gets called and how expensive it is to build the strings to be logged. In general it can become very expensive (calling Debug from tight loop while dynamically constructing strings to log), and the string construction cost remains even in the production build. That's why it's common practice in Java to have the guard outside.

E.g., call site looks like this if there's no guard or the guard is in Debug (here the string construction is just LDC, but it could be more complex, involving object allocation etc.):

```
public foo()V
   L0
    LINENUMBER 9 L0
    LDC "test"
    INVOKESTATIC core/Debug.p (Ljava/lang/String;)V
   L1
    LINENUMBER 10 L1
    RETURN
   L2
    LOCALVARIABLE this Lcore/TestClass; L0 L2 0
    MAXSTACK = 1
    MAXLOCALS = 1
```

And with guard at the call site:

```
public foo()V
   L0
    LINENUMBER 12 L0
    RETURN
   L1
    LOCALVARIABLE this Lcore/TestClass; L0 L1 0
    MAXSTACK = 0
    MAXLOCALS = 1
```

**Comment by akeranen** [comment]
OK, sounds reasonable. I'll fix the directory structure and EOLs now (in a few minutes). If you can rebase this fix to that version then, we should be able to avoid the superfluous whitespace changes.

**Comment by tk721** [comment]
Rebased to the new master, diffs are now garbage free.

**Pull request merged**
