### PR TITLE
Directory restructuring and whitespace fixes

### PR DESCRIPTION
**Pull request by akeranen**
Using now `src` for source files and `target` for binaries. Updated the scripts accordingly.
Credits to Florent Coriat for the whitespace fixing script.

### CODE REVIEW

**Comment by tk721** [comment]
Should the gui/buttonGraphics/ be stored in src/gui/buttonGraphics and copied over to target/ by the compile script? Would make more logical sense and makes it easier to set up the project in IDEs. E.g., IntelliJ builds into it's own directory structure under out/, which makes it difficult to get it to find the buttonGraphics when launching from the IDE.

**Comment by akeranen** [comment]
OK. In that case we'll need different compile script for Windows environment. Added first stab at that but can't test it because I don't have windows running here. And yes, admittedly most people will use IDE so they don't care about the scripts, but it it has turned out to be useful to have them for quick start.

**Comment by tk721** [comment]
I don't have a Windows machine to test on either, but this can be fixed later if needed. I'll merge this PR to continue with the other issues.

**Comment by akeranen** [comment]
I fixed the batch files too in the latest commit.

**Pull request merged**
